name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Add additional steps for deployment, testing, etc.
    - name: Log in to DockerHub
      run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login --username "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
      
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Navigate to frontend directory
      run: cd frontend

    - name: Install Dependencies
      run: yarn install

    - name: Build Frontend
      run: yarn build

    
